# Generated by Django 2.2 on 2020-10-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDosCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DedicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WebCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desk', models.TextField(blank=True)),
                ('nvme', models.TextField(blank=True)),
                ('sites', models.TextField(blank=True)),
                ('db', models.TextField(blank=True)),
                ('channel', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.WebCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Dedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desk', models.TextField(blank=True)),
                ('cpu', models.TextField(blank=True)),
                ('disk', models.TextField(blank=True)),
                ('ram', models.TextField(blank=True)),
                ('channel', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DedicCategory')),
            ],
        ),
        migrations.CreateModel(
            name='DDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desk', models.TextField(blank=True)),
                ('ports', models.TextField(blank=True)),
                ('protocol', models.TextField(blank=True)),
                ('ipv4', models.TextField(blank=True)),
                ('channel', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DedicCategory')),
            ],
        ),
    ]
