# Generated by Django 2.2 on 2020-10-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddoscategory',
            name='desk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dediccategory',
            name='desk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webcategory',
            name='desk',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ddos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DDosCategory'),
        ),
    ]
