# Generated by Django 2.2 on 2020-10-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201019_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedic',
            name='category',
        ),
        migrations.DeleteModel(
            name='DDos',
        ),
        migrations.DeleteModel(
            name='DDosCategory',
        ),
        migrations.DeleteModel(
            name='Dedic',
        ),
        migrations.DeleteModel(
            name='DedicCategory',
        ),
    ]
