# Generated by Django 2.2 on 2020-10-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_hosting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hosting',
        ),
    ]
