# Generated by Django 2.2 on 2020-10-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_hosting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vds',
            name='category',
        ),
        migrations.DeleteModel(
            name='Dedic',
        ),
        migrations.DeleteModel(
            name='Vds',
        ),
    ]
