# Generated by Django 2.2 on 2020-10-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201019_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Web',
        ),
        migrations.RenameModel(
            old_name='SubjectCategory',
            new_name='WebCategory',
        ),
    ]
