# Generated by Django 2.2 on 2020-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201030_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='cpu',
            field=models.CharField(max_length=128, verbose_name='Нагрузка на цп'),
        ),
        migrations.AlterField(
            model_name='web',
            name='db',
            field=models.CharField(max_length=128, verbose_name='БД'),
        ),
        migrations.AlterField(
            model_name='web',
            name='ddos',
            field=models.CharField(max_length=128, verbose_name='Защита от ДДОС'),
        ),
        migrations.AlterField(
            model_name='web',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание тарифа'),
        ),
        migrations.AlterField(
            model_name='web',
            name='disk',
            field=models.CharField(max_length=128, verbose_name='Дисковое пространство'),
        ),
        migrations.AlterField(
            model_name='web',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный тариф'),
        ),
        migrations.AlterField(
            model_name='web',
            name='location',
            field=models.CharField(max_length=128, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='web',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='web',
            name='prise',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='web',
            name='site',
            field=models.CharField(max_length=128, verbose_name='Сайты'),
        ),
        migrations.AlterField(
            model_name='web',
            name='traffic',
            field=models.CharField(max_length=128, verbose_name='Трафик'),
        ),
    ]
