# Generated by Django 2.2 on 2020-10-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201019_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Web',
            new_name='WebHosting',
        ),
    ]
