# Generated by Django 2.2 on 2020-10-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201030_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='db',
            field=models.CharField(max_length=128, verbose_name='База Данных'),
        ),
        migrations.AlterField(
            model_name='web',
            name='is_active',
            field=models.BooleanField(verbose_name='Активный тариф'),
        ),
    ]
