# Generated by Django 2.2 on 2020-10-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201019_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebHosting',
            new_name='Web',
        ),
    ]
