# Generated by Django 2.2 on 2020-10-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201019_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web',
            old_name='desc',
            new_name='channel',
        ),
        migrations.RemoveField(
            model_name='web',
            name='hours',
        ),
        migrations.AddField(
            model_name='web',
            name='db',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='web',
            name='desk',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='web',
            name='nvme',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='web',
            name='sites',
            field=models.TextField(blank=True),
        ),
        migrations.RenameModel(
            old_name='WebCategory',
            new_name='Catalog',
        ),
        migrations.CreateModel(
            name='Dedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desk', models.TextField(blank=True)),
                ('cpu', models.TextField(blank=True)),
                ('disk', models.TextField(blank=True)),
                ('ram', models.TextField(blank=True)),
                ('channel', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Catalog')),
            ],
        ),
    ]
