# Generated by Django 2.2 on 2020-10-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201019_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='web',
            name='category',
        ),
        migrations.AddField(
            model_name='dedic',
            name='prise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='web',
            name='prise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dedic',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Catalog'),
        ),
        migrations.AlterField(
            model_name='web',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Catalog'),
        ),
    ]
