# Generated by Django 2.2 on 2020-10-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_vds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vds',
        ),
    ]
