# Generated by Django 2.2 on 2020-10-31 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_vds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('desc', models.TextField(blank=True, verbose_name='Описание тарифа')),
                ('prise', models.IntegerField(default=0, verbose_name='Цена')),
                ('disk', models.CharField(max_length=128, verbose_name='Дисковое пространство')),
                ('cpu', models.CharField(max_length=128, verbose_name='Процессор')),
                ('traffic', models.CharField(max_length=128, verbose_name='Трафик')),
                ('location', models.CharField(max_length=128, verbose_name='Локация')),
                ('ddos', models.CharField(max_length=128, verbose_name='Защита от ДДОС')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
            options={
                'verbose_name': 'Выделенный сервер',
                'verbose_name_plural': 'Выделенныйе сервера',
            },
        ),
    ]
