# Generated by Django 2.2 on 2020-10-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_dedic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dedic',
            options={'verbose_name': 'Выделенный сервер', 'verbose_name_plural': 'Выделенные сервера'},
        ),
        migrations.AddField(
            model_name='dedic',
            name='ram',
            field=models.CharField(max_length=20, null=True, verbose_name='Оперативная память'),
        ),
    ]
