# Generated by Django 2.2 on 2020-10-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201019_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddos',
            name='category',
        ),
        migrations.AlterField(
            model_name='ddos',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Catalog'),
        ),
    ]
