# Generated by Django 2.2 on 2020-10-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20201019_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('hours', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dedic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='web',
            name='name',
        ),
        migrations.RenameModel(
            old_name='Catalog',
            new_name='SubjectCategory',
        ),
        migrations.DeleteModel(
            name='DDos',
        ),
        migrations.DeleteModel(
            name='Dedic',
        ),
        migrations.DeleteModel(
            name='Web',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.SubjectCategory'),
        ),
    ]
