# Generated by Django 2.2 on 2020-10-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20201031_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='Картинка'),
        ),
    ]
