# Generated by Django 2.2 on 2020-11-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('desc', models.TextField(blank=True, verbose_name='Описание тарифа')),
                ('prise', models.IntegerField(default=0, verbose_name='Цена')),
                ('disk', models.CharField(max_length=128, verbose_name='Дисковое пространство')),
                ('site', models.CharField(blank=True, max_length=128, verbose_name='Сайты')),
                ('db', models.CharField(blank=True, max_length=128, verbose_name='База Данных')),
                ('cpu', models.CharField(max_length=128, verbose_name='Нагрузка на цп')),
                ('ram', models.CharField(blank=True, max_length=128, verbose_name='Оперативная память')),
                ('traffic', models.CharField(max_length=128, verbose_name='Трафик')),
                ('location', models.CharField(max_length=128, verbose_name='Локация')),
                ('ddos', models.CharField(max_length=128, verbose_name='Защита от ДДОС')),
                ('is_active', models.BooleanField(verbose_name='Активный тариф')),
                ('image', models.ImageField(null=True, upload_to='img', verbose_name='Картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
            options={
                'verbose_name': 'хостинг',
                'verbose_name_plural': 'хостинги',
            },
        ),
        migrations.RemoveField(
            model_name='web',
            name='category',
        ),
        migrations.DeleteModel(
            name='Dedic',
        ),
        migrations.DeleteModel(
            name='Web',
        ),
    ]
