# Generated by Django 2.2 on 2020-10-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20201019_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True)),
                ('prise', models.IntegerField(default=0)),
                ('cpu', models.CharField(max_length=128)),
                ('core', models.CharField(max_length=128)),
                ('ram', models.CharField(max_length=128)),
                ('disk', models.CharField(max_length=128)),
                ('ipv4', models.CharField(max_length=128)),
                ('traffic', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('ddos', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
        ),
    ]
