# Generated by Django 2.2 on 2020-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20201106_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='image',
            field=models.ImageField(null=True, upload_to='hosting', verbose_name='Картинка'),
        ),
    ]
