# Generated by Django 2.2 on 2020-10-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_vds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedic',
            name='prise_day',
            field=models.IntegerField(default=0),
        ),
    ]
