# Generated by Django 2.2 on 2020-10-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_dedic_prise_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='vds',
            options={'verbose_name': 'Выделенный сервер', 'verbose_name_plural': 'Выделенные сервера'},
        ),
        migrations.AlterModelOptions(
            name='web',
            options={'verbose_name': 'Веб', 'verbose_name_plural': 'Веб'},
        ),
        migrations.AlterField(
            model_name='web',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
