# Generated by Django 2.2 on 2020-10-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20201019_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dedic',
            options={'verbose_name': 'Выделенный сервер', 'verbose_name_plural': 'Выделенные сервера'},
        ),
        migrations.AlterModelOptions(
            name='vds',
            options={'verbose_name': 'Виртуальный сервер', 'verbose_name_plural': 'Виртуальные сервера'},
        ),
    ]
