# Generated by Django 2.2 on 2020-10-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20201019_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vds',
            name='category',
        ),
        migrations.DeleteModel(
            name='Dedic',
        ),
        migrations.DeleteModel(
            name='VDS',
        ),
    ]
