# Generated by Django 2.2 on 2020-11-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostingBasket',
        ),
    ]
