# Generated by Django 2.2 on 2020-11-14 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0015_auto_20201106_1925'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basketapp', '0002_delete_hostingbasket'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Hosting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
